language: java
services: docker
deploy:
- provider: heroku
  on:
    branch: master
  app: my-geiger-app-ci
  api_key:
    secure: vcHkL8iAIPuHLDKh0QjAVRamP8Z3G8sKl+2U1kMXgE/gMzWM4DjhdyvWYhfebFhH6nxEgTNqVJFUNoRTQQnUV/iE/hDXSN8zRPE4jgUro1IfgPC3i8M3at8JRaq4KvHQ7YhbHXHsjpVrWaHi8X7kU7CLua8DCHDIq0r8dbaKV7/K1IjmUvU+GlirCeePpjrh3J4n+1+xdyRdpRdeDcKtkBimVAEakQGZseSAXXshYB3Pge7xfUwUzAkgKNIQ5ZjxgAJL1MDDtK3tLbjskKzkfmpcUypLLpYruSLMo0rPN718r87bTUlcwnQurBqrKAxD5xVibXILgM5vj1MCJ1327faZMzknG30YOWQ3dedDFA8No3JfTub6ySKUQ5YF0vsBv8+4kOuVxbR7HG2blAgG957MhhGxQPD+6YmQKJUvAffqC5LedHDALGMgTpkQJjOSfm5vUKrP6+FkWuGZwiJdP+ctJCEXXtrEejAX2G9BYn9f9fm4J0Y8g4Kk9O1bMy7NrIRKrtAcmWAw/sAU5ZBvShDo37NAyX3nRJOqSQZYwBIGZHnLYWH30jAZZZo87s0t43s6LYdaG3XUc7ZwcLdPiP7fRYAdfZlcU1k9iZIXGFC+jYBQVelNCHz1MxBLrLrkLQdGQqI09Ze71WohCR6iQ4ctMxni6PpLV3LGDr2OkYs=
- provider: script
  skip_cleanup: true
  script: bash docker_push.sh
  on:
    branch: master
before_install:
- chmod +x mvnw
env:
  global:
  - secure: gO0TW4mf3+JJPqBMU/gGXeObU2kMcuBiweZ+q4MLPziSq/ya/AcabrI0/yUgUwb7utVr5mV0Z3AclOpwrKhySnrUbanwzx2Dy7eybfAN397XPvDAg3wmvXv/DgLMKc8V3VXTldnmzv6Hi1aDqrV8NQDBvqxFkh0e9nXYWX2u54RjNfKnGb8MthFtNmm5aAVlq7204zCDf6UoqW1WAC/i4k8DsvdFpocjS4hZqj7D07jvXYxVo4AwGt7zc0HTVNQaDqiLSikaCTNEKNR2XDeb12RLN6anEhhY0rScdyRY0edGfyDF6g5MgPX7W61JCgmfOGfYUw9A3K4aaEVXAwQHGBJCc4TeODgPjIhlw83H7WAdYNc5FSQbVk6KP/HZf8vTgFDkGfQDNYy9ktBeUKoC9Yj6lNEg2ltepdQR8Zue0MVLDZTbdzVXMJcIPwGlTlvqOpFevcAomN9GfnWoslD2IvELAGbr9FkIqjEhSgmxROlaR+lbRonpIFKdJ2guUMllVdOxSSAjl/iznc6NLRx1LEDkCFybi/N0fU9Coa2/601xMdLOmLK/ijwAyaQBqPCnDCWwWrLpAqmPOpnufJ9g2scyZF2eQQS+tWxFeN/wR0hmnUEWADGJkhLCZ9mgDkS2OLWPFhechXTveBmFJdhcdoPAUYSlSpfKBzyZas9g4bw=
  - secure: VgTnqxIhVdI88d3fZFDpPcmIk80Cr+swzFQ1KhL839XczOutQPk7mpA9j9Z1k/0Gb/JrSOjgTsAzXcgUaHOAN2ly8y0FXt+jfoEf4JJPLPbhDDuNygLg/6oHKTCtQceEc+S4NSjoxE7xh/HZD+BO1IblVTL26X0yZ0OUACJ3spbCnlSM7+TZLv6ettfauTYa7yOeH5yXIj47JU/MX/vNkqru/AJdIUZ1tNOMaUgM4jkx7Hek8OuSEqdOvk6NHdH3vaY4tZ67RAhn3PioRCRS1488Sl13QvRkPFfY270AVAdM9vMvIEqDHyF2zDzTG0G3cayIq4HRHgaP9kU129NSD4E8v+V6h+TuTvNgpVLTHRb//+OhuoRVLh81hKIRNLgrSywsTm/ptAZP7K/aGPiBTa+G88T4/OgDxBeOuVTNZXPBV3YyAFRKo7+QIo6sozgwmj5FLRxVz6csxo8ZgxIUCuxOWP9DXmRFWTYFB2O+6E6bZXk/3Nlcg8gq8Q0l5wh+SC8sfpxu6jGKoNbUCFdqkuNMfqkcKK3+raqO7W7FUdKNpyaN4AdLg4hAYnkMGSUaG5KaABuTq8sBTX4Ado2w+GShqbnXCoQOWKYc0O31k7mPKv9OUrl0Lzi9I7CV+ohgOm9QUiTyLlPoJpsgD/t47/p4oF1AcYbdEJJzETpgaCc=
